services:
  suggesterr:
    build:
      context: .
      dockerfile: Dockerfile.allinone
    container_name: suggesterr
    environment:
      # Required API Keys - Get these from:
      # TMDB: https://www.themoviedb.org/settings/api
      # Gemini: https://ai.google.dev/
      - TMDB_API_KEY=your-tmdb-api-key
      - GOOGLE_GEMINI_API_KEY=your-gemini-api-key
      
      # Security settings - Add your server IP/domain here
      - ALLOWED_HOSTS=localhost,127.0.0.1,your-server-ip,your-domain.com
      - FORCE_SSL=False
      - DEBUG=True
      # Optional - Custom CSRF trusted origins (for reverse proxies)
      # - CSRF_TRUSTED_ORIGINS=http://your-server-ip:6789,https://your-domain.com
      
      # Optional - Admin user (created automatically on first run)
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_EMAIL=admin@suggesterr.local
      
      # Optional - Media server integration
      - JELLYFIN_URL=http://your-jellyfin-server:8096
      - JELLYFIN_API_KEY=your-jellyfin-api-key
      - PLEX_URL=http://your-plex-server:32400
      - PLEX_TOKEN=your-plex-token
      
      # Optional - Download management
      - RADARR_URL=http://your-radarr-server:7878
      - RADARR_API_KEY=your-radarr-api-key
      - SONARR_URL=http://your-sonarr-server:8989
      - SONARR_API_KEY=your-sonarr-api-key
      
      - TZ=Etc/UTC
    volumes:
      - /path/to/suggesterr/config:/config
    ports:
      - 8000:8000
    restart: unless-stopped
