version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: suggesterr
      POSTGRES_USER: suggesterr
      POSTGRES_PASSWORD: suggesterr
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://suggesterr:suggesterr@db:5432/suggesterr
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@suggesterr.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - LOAD_INITIAL_DATA=false
      - FORCE_SSL=false
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      # Load environment variables from .env file
      - TMDB_API_KEY=${TMDB_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
    env_file:
      - .env

  celery:
    build: .
    command: celery -A suggesterr worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://suggesterr:suggesterr@db:5432/suggesterr
      - REDIS_URL=redis://redis:6379/0
      - TMDB_API_KEY=${TMDB_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A suggesterr beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://suggesterr:suggesterr@db:5432/suggesterr
      - REDIS_URL=redis://redis:6379/0
      - TMDB_API_KEY=${TMDB_API_KEY}
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - JELLYFIN_URL=${JELLYFIN_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - PLEX_URL=${PLEX_URL}
      - PLEX_TOKEN=${PLEX_TOKEN}
      - RADARR_URL=${RADARR_URL}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - SONARR_URL=${SONARR_URL}
      - SONARR_API_KEY=${SONARR_API_KEY}
    env_file:
      - .env

volumes:
  postgres_data: