# Generated by Django 4.2.7 on 2025-07-16 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('original_title', models.CharField(blank=True, max_length=500)),
                ('overview', models.TextField(blank=True)),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('number_of_episodes', models.IntegerField(blank=True, null=True)),
                ('number_of_seasons', models.IntegerField(blank=True, null=True)),
                ('episode_run_time', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_on_jellyfin', models.BooleanField(default=False)),
                ('available_on_plex', models.BooleanField(default=False)),
                ('requested_on_sonarr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, to='core.genre')),
            ],
            options={
                'ordering': ['-popularity', '-vote_average'],
            },
        ),
        migrations.CreateModel(
            name='TVShowWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tv_show')},
            },
        ),
        migrations.CreateModel(
            name='TVShowRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('user', 'tv_show')},
            },
        ),
        migrations.CreateModel(
            name='TVShowRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tv_show')},
            },
        ),
    ]
