# Generated by Django 4.2.7 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='tv_rating',
            field=models.CharField(blank=True, choices=[('TV-Y', 'All Children'), ('TV-Y7', 'Children 7+'), ('TV-G', 'General Audience'), ('TV-PG', 'Parental Guidance'), ('TV-14', 'Parents Strongly Cautioned'), ('TV-MA', 'Mature Audiences')], max_length=10),
        ),
    ]
