# Generated by Django 4.2.7 on 2025-07-16 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radarr_url', models.URLField(blank=True, null=True)),
                ('radarr_api_key', models.CharField(blank=True, max_length=255)),
                ('sonarr_url', models.URLField(blank=True, null=True)),
                ('sonarr_api_key', models.CharField(blank=True, max_length=255)),
                ('server_type', models.CharField(blank=True, choices=[('jellyfin', 'Jellyfin'), ('plex', 'Plex')], max_length=20)),
                ('server_url', models.URLField(blank=True, null=True)),
                ('server_api_key', models.CharField(blank=True, max_length=255)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('blue', 'Blue'), ('green', 'Green')], default='dark', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
