# Generated by Django 4.2.7 on 2025-07-25 20:42

import accounts.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI')], default='gemini', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='openai_api_key',
            field=accounts.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='radarr_api_key',
            field=accounts.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='radarr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='server_api_key',
            field=accounts.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='server_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='sonarr_api_key',
            field=accounts.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='sonarr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
