# Generated by Django 4.2.7 on 2025-07-17 17:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0008_movie_mpaa_rating'),
        ('tv_shows', '0002_tvshow_tv_rating'),
        ('accounts', '0002_familyprofile_profilelimits_contentrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_requests', models.BooleanField(default=True)),
                ('auto_approve_admin', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_request_limit', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('weekly_request_limit', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('monthly_request_limit', models.PositiveIntegerField(default=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('daily_viewing_limit', models.PositiveIntegerField(default=120, help_text='Daily viewing limit in minutes')),
                ('weekly_viewing_limit', models.PositiveIntegerField(default=840, help_text='Weekly viewing limit in minutes')),
                ('bedtime_hour', models.PositiveIntegerField(default=21, help_text='Hour when content access is restricted (24-hour format)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('wakeup_hour', models.PositiveIntegerField(default=7, help_text='Hour when content access is allowed (24-hour format)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('weekend_extended_hours', models.BooleanField(default=True, help_text='Allow extended hours on weekends')),
                ('weekend_bedtime_hour', models.PositiveIntegerField(default=23, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('temporary_access', models.BooleanField(default=False)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('proposed_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('proposed_max_movie_rating', models.CharField(default='G', max_length=10)),
                ('proposed_max_tv_rating', models.CharField(default='TV-Y', max_length=10)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.familygroup')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContentFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('movie', 'Movie'), ('tv_show', 'TV Show')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_blocked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(help_text='User who blocked this content', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_content', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie'), ('user', 'tv_show')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('content_view', 'Content Viewed'), ('content_request', 'Content Requested'), ('request_approved', 'Request Approved'), ('request_denied', 'Request Denied'), ('content_blocked', 'Content Blocked'), ('limit_exceeded', 'Limit Exceeded'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='accounts_us_user_id_64ef8c_idx'), models.Index(fields=['user', 'timestamp'], name='accounts_us_user_id_f07708_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('max_movie_rating', models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], default='G', max_length=10)),
                ('max_tv_rating', models.CharField(choices=[('TV-Y', 'All Children'), ('TV-Y7', 'Children 7+'), ('TV-G', 'General Audience'), ('TV-PG', 'Parental Guidance'), ('TV-14', 'Parents Strongly Cautioned'), ('TV-MA', 'Mature Audiences')], default='TV-Y', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.familygroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__username'],
                'unique_together': {('user', 'family')},
            },
        ),
        migrations.CreateModel(
            name='ApprovedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_reason', models.TextField(blank=True)),
                ('permanent_access', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_content_approvals', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('tv_show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tv_shows.tvshow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_approved_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'movie'), ('user', 'tv_show')},
            },
        ),
    ]
