# Generated by Django 4.2.7 on 2025-07-25 20:52

import accounts.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersettings_ai_provider_usersettings_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gemini_api_key',
            field=accounts.encryption.EncryptedCharField(blank=True, max_length=500),
        ),
    ]
