# Generated by Django 4.2.7 on 2025-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('movies', '0004_usernegativefeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='genres',
        ),
        migrations.AlterUniqueTogether(
            name='tvshowrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tvshowrating',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='tvshowrating',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tvshowrecommendation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tvshowrecommendation',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='tvshowrecommendation',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='tvshowwatchlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tvshowwatchlist',
            name='tv_show',
        ),
        migrations.RemoveField(
            model_name='tvshowwatchlist',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usernegativefeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usernegativefeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='core.genre'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='TVShow',
        ),
        migrations.DeleteModel(
            name='TVShowRating',
        ),
        migrations.DeleteModel(
            name='TVShowRecommendation',
        ),
        migrations.DeleteModel(
            name='TVShowWatchlist',
        ),
        migrations.DeleteModel(
            name='UserNegativeFeedback',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
