# Generated by Django 4.2.7 on 2025-07-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_tvshow_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='available_on_jellyfin',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='available_on_plex',
        ),
    ]
