# Generated by Django 4.2.7 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_fix_poster_path_null_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(blank=True, choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=10),
        ),
    ]
