# Generated by Django 4.2.7 on 2025-07-17 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0002_chatconversation_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('scale', 'Scale (1-5)'), ('text', 'Text Response')], max_length=20)),
                ('answer_options', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(default='general', max_length=50)),
                ('trait_mapping', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_traits', models.JSONField(blank=True, default=dict)),
                ('quiz_completed', models.BooleanField(default=False)),
                ('quiz_completed_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_genres', models.JSONField(blank=True, default=list)),
                ('preferred_decades', models.JSONField(blank=True, default=list)),
                ('content_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personality_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
